### ISSUE TITLE
p110, 「③では」

### ISSUE THREAD

**Issue by externvoid** [kkeeth/riot4-book-support#11]
p109掲載のtodo.riotのコメント//③で始まるコードに関して、p110, 「③では」から始まる段落で説明されています。
しかし、コードには説明されている処理が記載されていません。

p110, 「③では」から始まる段落で説明されているコードはどの箇所でしょうか？

**Comment by kkeeth** [comment]
> p109掲載のtodo.riotのコメント//③で始まるコードに関して、p100, 「③では」から始まる段落で説明されています。
しかし、コードには説明されている処理が記載されていません。

P109の //③ の説明については、P110 の ③では〜 で説明しておりますー。

> p100, 「③では」から始まる段落で説明されているコードはどの箇所でしょうか？

こちらについては P99 の `todo.riot` 内にありますー。

**Comment by externvoid** [comment]
IssueのSubjectを誤って記述してしまいました。申し訳無かったです。
誤り
p100, 「③では」 
正解
p110, 「③では」

>P109の //③ の説明については、P110 の ③では〜 で説明しておりますー。

とのことですが、p110の「③では〜 」の箇所ではボタンの非活性化のためのコードに言及されてます。しかし、p109のコードにはその様な箇所が見当たりません。

**Comment by kkeeth** [comment]
@externvoid 

回答が遅くなって申し訳ございません。

> とのことですが、p110の「③では〜 」の箇所ではボタンの非活性化のためのコードに言及されてます。しかし、p109のコードにはその様な箇所が見当たりません。

こちら再度読み直しましたが、ご指摘の通り P110 の `③では、〜` にて完了タスクのボタンの非活性化について説明しておりますが、この時点ではボタンの非活性化は行っておらず、また `state.hasDoneTodo` のパラメータも存在しておりませんでした。

同様に P112 の `一括削除のボタンは③で対象のtodoが存在しなければ非活性に〜` の記述も誤植となります。ただし、⑦でスタイルを調整しています。 の記述については正しい記述となります。


こちらにも追記致しました。本チャプターがボロボロで申し訳ないです…

https://github.com/kkeeth/riot4-book-support/blob/master/corrections/CHAPTER03.md

**Comment by externvoid** [comment]
回答有難う御座いました。
CHAPTER3のrefactoring前のコードをriot4-book-example-appsへ加えて頂けると有り難いです。
お手数ですが、ご検討お願いします。

**Comment by kkeeth** [comment]
@externvoid 

> CHAPTER3のrefactoring前のコードをriot4-book-example-appsへ加えて頂けると有り難いです。

以下に用意させていただきましたので、ご確認いただければと思います。

https://github.com/kkeeth/riot4-book-example-apps/tree/master/CHAPTER3/delete-todos

念の為、チャプター３の各セクション終了毎のソースコードも用意しておりますので、ご参考までに 🙇 

https://github.com/kkeeth/riot4-book-example-apps/tree/master/CHAPTER3/

**Comment by kkeeth** [comment]
本件クローズさせていただきます。
