### ISSUE TITLE
p92記載のplnkrデモ

### ISSUE THREAD

**Issue by externvoid** [kkeeth/riot4-book-support#12]
p92記載のURL

https://run.plnkr.co/preview/ck8em6dla001a2a6lbxtc9nbd

へアクセス出来ません。TODOアプリのデモです。

**Comment by kkeeth** [comment]
ご指摘ありがとうございます！
申し訳ないです🙇 Plunker はソースを更新して保存する度にデモのURLが変更されることを失念しており、手を加えてしまっておりました。以下のURLを記載すべきでした。

https://plnkr.co/plunk/Uoghj8aOznPhxdoQ6GHJ

以下のページも更新しておきましたので、こちらのissueはクローズさせていただきます。

https://github.com/kkeeth/riot4-book-support/blob/master/corrections/CHAPTER03.md
