### ISSUE TITLE
p111 newTask

### ISSUE THREAD

**Issue by externvoid** [kkeeth/riot4-book-support#13]
ソースコード中にnewTask配列あるいはオブジェクトを展開している部分があります。

```
...newTask
```

newTaskにはどこで値がセットされるのでしょうか？

**Comment by kkeeth** [comment]
@externvoid 

こちら、回答が遅くなってしまい申し訳ございません。

> newTaskにはどこで値がセットされるのでしょうか？

はい、ご指摘の通りこの時点では `...newTask` のパラメータは一度も記述したことがないため完全に誤植となります。

同様に、P119, P120 も誤植となります 🙇 

こちらにも追記致しました。
https://github.com/kkeeth/riot4-book-support/blob/master/corrections/CHAPTER03.md

**Comment by kkeeth** [comment]
こちらはクローズさせていただきます。
