### ISSUE TITLE
pp112 updateHasDoneTodo

### ISSUE THREAD

**Issue by externvoid** [kkeeth/riot4-book-support#14]
掲題のメソッドは誤記で、正解はcheckDoneTodoですよねぇ？

ぁあ、ようやくコードが解読出来きた。

**Comment by kkeeth** [comment]
コメントありがとうございます🙇仰る通りで、`checkDoneTodo` が正解です…以下追記いたしましたので、こちらクローズさせていただきます。ご指摘いただき助かりました！

https://github.com/kkeeth/riot4-book-support/blob/master/corrections/CHAPTER03.md
