### ISSUE TITLE
p201 参照ページ誤り

### ISSUE THREAD

**Issue by AlpsStlo** [kkeeth/riot4-book-support#6]
201ページの中間に

```
これは個人的な見解ですが、78ページでもお話したように、...
```

とありますが、初版では78ページではなく、82ページにありました。

**Comment by kkeeth** [comment]
ご指摘ありがとうございます！
こちらも追記致しましたので、クローズさせていただきます 🙇 

https://github.com/kkeeth/riot4-book-support/blob/master/corrections/CHAPTER05.md
